moved login password to conf file

diff --git a/diskpublish b/diskpublish
--- a/diskpublish
+++ b/diskpublish
@@ -1,12 +1,12 @@
 #!/bin/bash
 
-LOGIN=your_login
-PASS=your_password
 HOST=webdav.yandex.ru
 SUBFOLDER=/public
 
+test -f ~/.diskpublish.conf || { echo -e "Missing file ~/.diskpublish.conf. Create it and fill in your login password in this way:\nLOGIN=***\nPASS=***" >&2; exit 1; }
+. ~/.diskpublish.conf
 if [ "$#" -ne "1" ]; then
-   echo "Usage: $0 <file>"
+   echo "Usage: $0 <file>" >&2
    exit 1
 fi
 
